In [5]:
import numpy as np
from numpy import linalg 

In [6]:
A = np.array([[6, 1, 1],[4, -2, 5], [2, 8, 7]])
 

print("Rank of A:", np.linalg.matrix_rank(A))

print("\nTrace of A:", np.trace(A))
 

print("\nDeterminant of A:", np.linalg.det(A))
 

print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, -1))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]


In [11]:
a = np.array([[1, -2], [2, 5]])

print("Array is:", a)


out1,out2 = linalg.eigh(a)

print("Eigenvalues are:", out1)
print("Eigenvectors are:", out2)
#SVM
#PCA
#linear reg
#corr
#k fold




Array is: [[ 1 -2]
 [ 2  5]]
Eigenvalues are: [0.17157288 5.82842712]
Eigenvectors are: [[-0.92387953  0.38268343]
 [ 0.38268343  0.92387953]]
